export const lang = {
  en: {
    closingPrice: "Closing Price",
    dailyRange: "Daily range",
    dailyVolume: "Daily volume",
    weekVolume52: "52-week volume",
    weekRange52: "52-week range",
    marketKapitalization: "Market kapitalization",
    monthChange: "Month change",
    yearChange: "Year change",
    inCasesOfCapitalization: "In cases of capitalization",
    bookValue: "Book value",
    targetPrice: "Target price",
    liquidityIndicator: "Liquidity indicator",
    chooseQuarter: "Choose a quarter",
    chooseYear: "Choose a year",
    authorizedCapital: "Authorized capital",
    commonShares: "Common shares",
    preferredShares: "Preferred shares",
    faceValue: "Face value",
    assets: "Assets",
    equity: "Equity",
    retainedEarnings: "Retained earnings",
    liabilities: "Liabilities",
    longTermLiabilities: "Long term liabilities",
    shortTermLiabilities: "Short term liabilities",
    revenue: "Revenue",
    netProfit: "Net profit",
    cash: "Cash",
    dividends: "Dividends",
    marketData: "Market data",
    all: "All",
    sec: "Securities",
    bond: "Bonds",
    searchBy: "Search by Ticker",
    ticker: "Ticker",
    comp: "Company",
    lastPrice: "Last Price",
    change: "Change",
    changePercentage: "Change, %",
    volume: "Volume",
    marketCap: "Market Capitalization",
    graphM: "Graph (M)",
    usd: "USD",
    noRec: "No records",
    profile: "Profile",
    financeIndicator: "finance indicator",
    balance: "Balance",
    financialReport: "Financial report",
    analytics: "Analytics",
    thisQuarterAbsent: "This quarter is absent",

  },

  ru: {
    closingPrice: "Цена закрытия ",
    dailyRange: "Дневной диапозон ",
    dailyVolume: "Дневной объем ",
    weekVolume52: "52 недельный объем",
    weekRange52: "52 недельный диапазон",
    marketKapitalization: "Рыночная капитализация ",
    monthChange: "Изменение за месяц ",
    yearChange: "Изменение за год",
    inCasesOfCapitalization: "В случаи капитализации ",
    bookValue: "Балансовая стоимость ",
    targetPrice: "Ожидаемая цена ",
    liquidityIndicator: "Индикатор ликвидности ",
    chooseQuarter: "Выберете квартал",
    chooseYear: "Выберете год ",
    authorizedCapital: "Уставной капитал ",
    commonShares: "Простые акции ",
    preferredShares: "Привилигированные акции ",
    faceValue: "Номинальная стоимость ",
    assets: "Активы ",
    equity: "Собственный капитал ",
    retainedEarnings: "Нераспределенная прибыль ",
    liabilities: "Обязательства ",
    longTermLiabilities: "Долгосрочные обязательства ",
    shortTermLiabilities: "Краткосрочные обязательства ",
    revenue: "Выручка ",
    netProfit: "Чистая прибыль ",
    cash: "Денежные средства ",
    dividends: "Дивиденды ",
    marketData: "Рыночные данные",
    all: "Все",
    sec: "Акции",
    bond: "Облигации",
    searchBy: "Поиск по тикеру",
    ticker: "Тикер",
    comp: "Компания",
    lastPrice: "Последняя цена",
    change: "Изменение",
    changePercentage: "Изменение, %",
    volume: "Объём",
    marketCap: "Рыночная капитализация",
    graphM: "График за месяц",
    usd: "В USD",
    noRec: "Нет записей",
    profile: "Профиль",
    financeIndicator: "Финансовые показатели",
    balance: "Баланс",
    financialReport: "Финансовый отчет",
    analytics: "Аналитика",
    thisQuarterAbsent: "Данный квартал отсуствует",
  },
  uz: {
    closingPrice: "Oxirgi narx",
    dailyRange: "Kun oralig’i",
    dailyVolume: "Kunlik savdo hajmi",
    weekVolume52: "52 haftalik savdo hajmi",
    weekRange52: "52 hafta oralig’i",
    marketKapitalization: "Bozor kapitallashuvi",
    monthChange: "Oylik o’zgarish ",
    yearChange: "Yillik o’zgarish ",
    inCasesOfCapitalization: "Kapitalizatsiya holati",
    bookValue: "Balans narxi",
    targetPrice: "Kutilayotgan narx",
    liquidityIndicator: "Likvidlik ko’rsatkichi",
    chooseQuarter: "Chorakni tanlang",
    chooseYear: "Yilni tanlang",
    authorizedCapital: "Ustav kapitali",
    commonShares: "Oddiy aktsiyalari",
    preferredShares: "Imtiyozli aktsiyalar",
    faceValue: "Nominal qiymat",
    assets: "Aktivlar",
    equity: "Xususiy kapital",
    retainedEarnings: "Taqsimlanmagan foyda",
    liabilities: "Majburiyatlar",
    longTermLiabilities: "Uzoq muddatli majburiyatlar",
    shortTermLiabilities: "Qisqa muddatli majburiyatlar",
    revenue: "Daromad",
    netProfit: "Sof foyda ",
    cash: "Pul mablag’lari ",
    dividends: "Dividendlar",
    marketData: "Bozor Ma’lumotlari",
    all: "Barchasi",
    sec: "Aktsiya",
    bond: "Obligatsiya",
    searchBy: "Tiker orqali qidirish",
    ticker: "Tiker",
    comp: "Kompaniya",
    lastPrice: "Oxirgi narx",
    change: "O’zgarish",
    changePercentage: "O’zgarish, %",
    volume: "Hajm",
    marketCap: "Bozor kapitallashuvi",
    graphM: "Oylik jadval",
    usd: "USD",
    noRec: "Ma’lumot yo’q",
    profile: "Profil",
    financeIndicator: "Moliyaviy ko'rsatkichlar",
    balance: "Muvozanat",
    financialReport: "Moliyaviy hisobot",
    analytics: "Tahlil",
    thisQuarterAbsent: "Ushbu chorak yo'q",
  }
};